/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s272_1
#  OS:                Linux x86_64(Host ID ws35)
#  Generated on:      Thu May 19 19:45:36 2016
#  Design:            gcd
#  Command:           saveNetlist gcd_lvs.v -includePowerGround
###############################################################
*/
module CLKBUFX3 (
	Y, 
	A, 
	VDD, 
	VSS);
   output Y;
   input A;
   inout VDD;
   inout VSS;
endmodule

module DLY2X1 (
	Y, 
	A, 
	VDD, 
	VSS);
   output Y;
   input A;
   inout VDD;
   inout VSS;
endmodule

module CLKINVX8 (
	Y, 
	A, 
	VDD, 
	VSS);
   output Y;
   input A;
   inout VDD;
   inout VSS;
endmodule

module ADDFX2 (
	S, 
	CO, 
	CI, 
	B, 
	A, 
	VDD, 
	VSS);
   output S;
   output CO;
   input CI;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module XOR3X2 (
	Y, 
	C, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input C;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module INVX1 (
	Y, 
	A, 
	VDD, 
	VSS);
   output Y;
   input A;
   inout VDD;
   inout VSS;
endmodule

module XNOR2X1 (
	Y, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module NAND2X1 (
	Y, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module DFFRHQX1 (
	RN, 
	Q, 
	D, 
	CK, 
	VDD, 
	VSS);
   input RN;
   output Q;
   input D;
   input CK;
   inout VDD;
   inout VSS;
endmodule

module DFFRXL (
	RN, 
	QN, 
	Q, 
	D, 
	CK, 
	VDD, 
	VSS);
   input RN;
   output QN;
   output Q;
   input D;
   input CK;
   inout VDD;
   inout VSS;
endmodule

module DFFXL (
	QN, 
	Q, 
	D, 
	CK, 
	VDD, 
	VSS);
   output QN;
   output Q;
   input D;
   input CK;
   inout VDD;
   inout VSS;
endmodule

module NOR2X1 (
	Y, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module AOI221X1 (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module AOI21X1 (
	Y, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module AOI22X1 (
	Y, 
	B1, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module OAI21XL (
	Y, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module OAI22X1 (
	Y, 
	B1, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module OAI222XL (
	Y, 
	C1, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input C1;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module NAND4X1 (
	Y, 
	D, 
	C, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input D;
   input C;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module AND4X2 (
	Y, 
	D, 
	C, 
	B, 
	A, 
	VDD, 
	VSS);
   output Y;
   input D;
   input C;
   input B;
   input A;
   inout VDD;
   inout VSS;
endmodule

module AOI32X1 (
	Y, 
	B1, 
	B0, 
	A2, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input B1;
   input B0;
   input A2;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module NOR2BX1 (
	Y, 
	B, 
	AN, 
	VDD, 
	VSS);
   output Y;
   input B;
   input AN;
   inout VDD;
   inout VSS;
endmodule

module OAI221XL (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0, 
	VDD, 
	VSS);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
   inout VDD;
   inout VSS;
endmodule

module OAI2BB1X1 (
	Y, 
	B0, 
	A1N, 
	A0N, 
	VDD, 
	VSS);
   output Y;
   input B0;
   input A1N;
   input A0N;
   inout VDD;
   inout VSS;
endmodule

/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s272_1
#  OS:                Linux x86_64(Host ID ws34)
#  Generated on:      Thu May 19 18:55:23 2016
#  Design:            gcd
###############################################################
*/
module gcd_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO, 
	VDD, 
	VSS);
   input [7:0] A;
   input [7:0] B;
   input CI;
   output [7:0] DIFF;
   output CO;
   inout VDD;
   inout VSS;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire [7:1] carry;

   // Module instantiations
   ADDFX2 U2_1 (
	.S(DIFF[1]),
	.CO(carry[2]),
	.CI(carry[1]),
	.B(n5),
	.A(A[1]), 
	.VDD(VDD), 
	.VSS(VSS));
   ADDFX2 U2_6 (
	.S(DIFF[6]),
	.CO(carry[7]),
	.CI(carry[6]),
	.B(n4),
	.A(A[6]), 
	.VDD(VDD), 
	.VSS(VSS));
   ADDFX2 U2_5 (
	.S(DIFF[5]),
	.CO(carry[6]),
	.CI(carry[5]),
	.B(n9),
	.A(A[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   ADDFX2 U2_4 (
	.S(DIFF[4]),
	.CO(carry[5]),
	.CI(carry[4]),
	.B(n8),
	.A(A[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   ADDFX2 U2_3 (
	.S(DIFF[3]),
	.CO(carry[4]),
	.CI(carry[3]),
	.B(n7),
	.A(A[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   ADDFX2 U2_2 (
	.S(DIFF[2]),
	.CO(carry[3]),
	.CI(carry[2]),
	.B(n6),
	.A(A[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   XOR3X2 U2_7 (
	.Y(DIFF[7]),
	.C(carry[7]),
	.B(n3),
	.A(A[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U1 (
	.Y(n3),
	.A(B[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   XNOR2X1 U2 (
	.Y(DIFF[0]),
	.B(A[0]),
	.A(n2), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U3 (
	.Y(n2),
	.A(B[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U4 (
	.Y(n6),
	.A(B[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U5 (
	.Y(n7),
	.A(B[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U6 (
	.Y(n8),
	.A(B[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U7 (
	.Y(n9),
	.A(B[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U8 (
	.Y(n4),
	.A(B[6]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U9 (
	.Y(n5),
	.A(B[1]), 
	.VDD(VDD), 
	.VSS(VSS));
   NAND2X1 U10 (
	.Y(carry[1]),
	.B(n1),
	.A(B[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U11 (
	.Y(n1),
	.A(A[0]), 
	.VDD(VDD), 
	.VSS(VSS));
endmodule

module gcd (
	A_in, 
	B_in, 
	clk, 
	rst_n, 
	out, 
	done, 
	VDD, 
	VSS);
   input [7:0] A_in;
   input [7:0] B_in;
   input clk;
   input rst_n;
   output [7:0] out;
   output done;
   inout VDD;
   inout VSS;

   // Internal wires
   wire FE_PHN16_n132;
   wire FE_PHN15_n74;
   wire FE_PHN14_n110;
   wire FE_PHN13_n113;
   wire FE_PHN12_n89;
   wire FE_PHN11_n77;
   wire FE_PHN10_n107;
   wire FE_PHN9_n92;
   wire FE_PHN8_n66;
   wire FE_PHN7_n83;
   wire FE_PHN6_n71;
   wire FE_PHN5_n80;
   wire FE_PHN4_n95;
   wire FE_PHN3_n86;
   wire FE_PHN2_rst_n;
   wire FE_PHN1_n101;
   wire FE_PHN0_n98;
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N1;
   wire clk__L1_N0;
   wire N10;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n139;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire [7:0] A;
   wire [7:0] B;
   wire [1:0] state;

   // Module instantiations
   CLKBUFX3 FE_PHC16_n132 (
	.Y(FE_PHN16_n132),
	.A(n132), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC15_n74 (
	.Y(FE_PHN15_n74),
	.A(n74), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC14_n110 (
	.Y(FE_PHN14_n110),
	.A(n110), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC13_n113 (
	.Y(FE_PHN13_n113),
	.A(n113), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC12_n89 (
	.Y(FE_PHN12_n89),
	.A(n89), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC11_n77 (
	.Y(FE_PHN11_n77),
	.A(n77), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC10_n107 (
	.Y(FE_PHN10_n107),
	.A(n107), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC9_n92 (
	.Y(FE_PHN9_n92),
	.A(n92), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC8_n66 (
	.Y(FE_PHN8_n66),
	.A(n66), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC7_n83 (
	.Y(FE_PHN7_n83),
	.A(n83), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC6_n71 (
	.Y(FE_PHN6_n71),
	.A(n71), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC5_n80 (
	.Y(FE_PHN5_n80),
	.A(n80), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC4_n95 (
	.Y(FE_PHN4_n95),
	.A(n95), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC3_n86 (
	.Y(FE_PHN3_n86),
	.A(n86), 
	.VDD(VDD), 
	.VSS(VSS));
   DLY2X1 FE_PHC2_rst_n (
	.Y(FE_PHN2_rst_n),
	.A(rst_n), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC1_n101 (
	.Y(FE_PHN1_n101),
	.A(n101), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKBUFX3 FE_PHC0_n98 (
	.Y(FE_PHN0_n98),
	.A(n98), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKINVX8 clk__L2_I1 (
	.Y(clk__L2_N1),
	.A(clk__L1_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKINVX8 clk__L2_I0 (
	.Y(clk__L2_N0),
	.A(clk__L1_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKINVX8 clk__L1_I1 (
	.Y(clk__L1_N1),
	.A(clk), 
	.VDD(VDD), 
	.VSS(VSS));
   CLKINVX8 clk__L1_I0 (
	.Y(clk__L1_N0),
	.A(clk), 
	.VDD(VDD), 
	.VSS(VSS));
   gcd_DW01_sub_0 sub_77 (
	.A(A),
	.B(B),
	.CI(1'b0),
	.DIFF({ N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27,
		N26 }), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 state_reg_1_ (
	.RN(n139),
	.Q(state[1]),
	.D(n191),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_7_ (
	.RN(n139),
	.Q(out[7]),
	.D(n183),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_6_ (
	.RN(n139),
	.Q(out[6]),
	.D(n184),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_1_ (
	.RN(n139),
	.Q(out[1]),
	.D(n189),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_2_ (
	.RN(n139),
	.Q(out[2]),
	.D(n188),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_3_ (
	.RN(n139),
	.Q(out[3]),
	.D(n187),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_4_ (
	.RN(n139),
	.Q(out[4]),
	.D(n186),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_5_ (
	.RN(n139),
	.Q(out[5]),
	.D(n185),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 out_reg_0_ (
	.RN(n139),
	.Q(out[0]),
	.D(n190),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRHQX1 done_reg (
	.RN(n139),
	.Q(done),
	.D(n191),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFRXL state_reg_0_ (
	.RN(FE_PHN2_rst_n),
	.QN(n198),
	.Q(state[0]),
	.D(n193),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_7_ (
	.QN(n164),
	.Q(B[7]),
	.D(n133),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_6_ (
	.QN(n200),
	.Q(B[6]),
	.D(n125),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_5_ (
	.QN(n154),
	.Q(B[5]),
	.D(n124),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_4_ (
	.QN(n156),
	.Q(B[4]),
	.D(n123),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_3_ (
	.QN(n158),
	.Q(B[3]),
	.D(n122),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_2_ (
	.QN(n160),
	.Q(B[2]),
	.D(n121),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_1_ (
	.QN(n201),
	.Q(B[1]),
	.D(n120),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL B_reg_0_ (
	.QN(n194),
	.Q(B[0]),
	.D(n135),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_7_ (
	.QN(n196),
	.Q(A[7]),
	.D(n134),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_6_ (
	.QN(n163),
	.Q(A[6]),
	.D(FE_PHN16_n132),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_5_ (
	.QN(n155),
	.Q(A[5]),
	.D(n131),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_4_ (
	.QN(n157),
	.Q(A[4]),
	.D(n130),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_3_ (
	.QN(n159),
	.Q(A[3]),
	.D(n129),
	.CK(clk__L2_N1), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_2_ (
	.QN(n161),
	.Q(A[2]),
	.D(n128),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_1_ (
	.QN(n162),
	.Q(A[1]),
	.D(n127),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   DFFXL A_reg_0_ (
	.QN(n195),
	.Q(A[0]),
	.D(n126),
	.CK(clk__L2_N0), 
	.VDD(VDD), 
	.VSS(VSS));
   NAND2X1 U136 (
	.Y(n136),
	.B(n199),
	.A(n198), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U137 (
	.Y(n181),
	.A(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U138 (
	.Y(n182),
	.A(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2X1 U140 (
	.Y(n67),
	.B(n144),
	.A(n116), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI221X1 U141 (
	.Y(n116),
	.C0(n56),
	.B1(n55),
	.B0(n192),
	.A1(n182),
	.A0(n198), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U142 (
	.Y(n192),
	.A(n65), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U143 (
	.Y(n197),
	.A(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U144 (
	.Y(n191),
	.A(n117), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI21X1 U145 (
	.Y(n117),
	.B0(n56),
	.A1(n55),
	.A0(n192), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U146 (
	.Y(n193),
	.A(n64), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U147 (
	.Y(n64),
	.B1(n199),
	.B0(n198),
	.A1(n65),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U148 (
	.Y(n139),
	.A(n144), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI21XL U151 (
	.Y(N10),
	.B0(n153),
	.A1(n164),
	.A0(A[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U152 (
	.Y(n131),
	.B1(n181),
	.B0(n155),
	.A1(FE_PHN1_n101),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U153 (
	.Y(n101),
	.B1(n144),
	.B0(A_in[5]),
	.A1(n139),
	.A0(n102), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U154 (
	.Y(n102),
	.C1(n136),
	.C0(n154),
	.B1(n167),
	.B0(n199),
	.A1(n197),
	.A0(n103), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U155 (
	.Y(n167),
	.A(A_in[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U156 (
	.Y(n130),
	.B1(n181),
	.B0(n157),
	.A1(FE_PHN0_n98),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U157 (
	.Y(n98),
	.B1(n144),
	.B0(A_in[4]),
	.A1(n139),
	.A0(n99), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U158 (
	.Y(n99),
	.C1(n136),
	.C0(n156),
	.B1(n168),
	.B0(n199),
	.A1(n197),
	.A0(n100), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U159 (
	.Y(n168),
	.A(A_in[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U160 (
	.Y(n129),
	.B1(n181),
	.B0(n159),
	.A1(FE_PHN4_n95),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U161 (
	.Y(n95),
	.B1(n144),
	.B0(A_in[3]),
	.A1(n139),
	.A0(n96), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U162 (
	.Y(n96),
	.C1(n136),
	.C0(n158),
	.B1(n169),
	.B0(n199),
	.A1(n197),
	.A0(n97), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U163 (
	.Y(n169),
	.A(A_in[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U164 (
	.Y(n128),
	.B1(n181),
	.B0(n161),
	.A1(FE_PHN9_n92),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U165 (
	.Y(n92),
	.B1(n144),
	.B0(A_in[2]),
	.A1(n139),
	.A0(n93), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U166 (
	.Y(n93),
	.C1(n136),
	.C0(n160),
	.B1(n170),
	.B0(n199),
	.A1(n197),
	.A0(n94), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U167 (
	.Y(n170),
	.A(A_in[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U168 (
	.Y(n127),
	.B1(n181),
	.B0(n162),
	.A1(FE_PHN12_n89),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U169 (
	.Y(n89),
	.B1(n144),
	.B0(A_in[1]),
	.A1(n139),
	.A0(n90), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U170 (
	.Y(n90),
	.C1(n136),
	.C0(n201),
	.B1(n171),
	.B0(n199),
	.A1(n197),
	.A0(n91), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U171 (
	.Y(n171),
	.A(A_in[1]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U172 (
	.Y(n132),
	.B1(n181),
	.B0(n163),
	.A1(n104),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U173 (
	.Y(n104),
	.B1(n144),
	.B0(A_in[6]),
	.A1(n139),
	.A0(n105), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U174 (
	.Y(n105),
	.C1(n136),
	.C0(n200),
	.B1(n166),
	.B0(n199),
	.A1(n197),
	.A0(n106), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U175 (
	.Y(n166),
	.A(A_in[6]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U176 (
	.Y(n134),
	.B1(n181),
	.B0(n196),
	.A1(FE_PHN14_n110),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U177 (
	.Y(n110),
	.B1(n144),
	.B0(A_in[7]),
	.A1(n139),
	.A0(n111), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U178 (
	.Y(n111),
	.C1(n164),
	.C0(n136),
	.B1(n165),
	.B0(n199),
	.A1(n197),
	.A0(n112), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U179 (
	.Y(n165),
	.A(A_in[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U180 (
	.Y(n126),
	.B1(n181),
	.B0(n195),
	.A1(FE_PHN3_n86),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U181 (
	.Y(n86),
	.B1(n144),
	.B0(A_in[0]),
	.A1(n139),
	.A0(n87), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U182 (
	.Y(n87),
	.C1(n136),
	.C0(n194),
	.B1(n172),
	.B0(n199),
	.A1(n197),
	.A0(n88), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U183 (
	.Y(n172),
	.A(A_in[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U184 (
	.Y(n120),
	.B1(n201),
	.B0(n181),
	.A1(n67),
	.A0(FE_PHN8_n66), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U185 (
	.Y(n66),
	.B1(n144),
	.B0(B_in[1]),
	.A1(n139),
	.A0(n68), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U186 (
	.Y(n68),
	.C1(n136),
	.C0(n162),
	.B1(n179),
	.B0(n199),
	.A1(n197),
	.A0(n69), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U187 (
	.Y(n179),
	.A(B_in[1]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U188 (
	.Y(n135),
	.B1(n194),
	.B0(n181),
	.A1(FE_PHN13_n113),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U189 (
	.Y(n113),
	.B1(n144),
	.B0(B_in[0]),
	.A1(n139),
	.A0(n114), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U190 (
	.Y(n114),
	.C1(n136),
	.C0(n195),
	.B1(n180),
	.B0(n199),
	.A1(n197),
	.A0(n115), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U191 (
	.Y(n180),
	.A(B_in[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U192 (
	.Y(n124),
	.B1(n154),
	.B0(n181),
	.A1(FE_PHN5_n80),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U193 (
	.Y(n80),
	.B1(n144),
	.B0(B_in[5]),
	.A1(n139),
	.A0(n81), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U194 (
	.Y(n81),
	.C1(n136),
	.C0(n155),
	.B1(n175),
	.B0(n199),
	.A1(n197),
	.A0(n82), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U195 (
	.Y(n175),
	.A(B_in[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U196 (
	.Y(n123),
	.B1(n156),
	.B0(n181),
	.A1(FE_PHN11_n77),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U197 (
	.Y(n77),
	.B1(n144),
	.B0(B_in[4]),
	.A1(n139),
	.A0(n78), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U198 (
	.Y(n78),
	.C1(n136),
	.C0(n157),
	.B1(n176),
	.B0(n199),
	.A1(n197),
	.A0(n79), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U199 (
	.Y(n176),
	.A(B_in[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U200 (
	.Y(n122),
	.B1(n158),
	.B0(n181),
	.A1(FE_PHN15_n74),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U201 (
	.Y(n74),
	.B1(n144),
	.B0(B_in[3]),
	.A1(n139),
	.A0(n75), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U202 (
	.Y(n75),
	.C1(n136),
	.C0(n159),
	.B1(n177),
	.B0(n199),
	.A1(n197),
	.A0(n76), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U203 (
	.Y(n177),
	.A(B_in[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U204 (
	.Y(n121),
	.B1(n160),
	.B0(n181),
	.A1(FE_PHN6_n71),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U205 (
	.Y(n71),
	.B1(n144),
	.B0(B_in[2]),
	.A1(n139),
	.A0(n72), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U206 (
	.Y(n72),
	.C1(n136),
	.C0(n161),
	.B1(n178),
	.B0(n199),
	.A1(n197),
	.A0(n73), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U207 (
	.Y(n178),
	.A(B_in[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U208 (
	.Y(n133),
	.B1(n164),
	.B0(n181),
	.A1(FE_PHN10_n107),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U209 (
	.Y(n107),
	.B1(n144),
	.B0(B_in[7]),
	.A1(n139),
	.A0(n108), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U210 (
	.Y(n108),
	.C1(n136),
	.C0(n196),
	.B1(n173),
	.B0(n199),
	.A1(n197),
	.A0(n109), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U211 (
	.Y(n173),
	.A(B_in[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI22X1 U212 (
	.Y(n125),
	.B1(n200),
	.B0(n181),
	.A1(FE_PHN7_n83),
	.A0(n67), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U213 (
	.Y(n83),
	.B1(n144),
	.B0(B_in[6]),
	.A1(n139),
	.A0(n84), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U214 (
	.Y(n84),
	.C1(n136),
	.C0(n163),
	.B1(n174),
	.B0(n199),
	.A1(n197),
	.A0(n85), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U215 (
	.Y(n174),
	.A(B_in[6]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U216 (
	.Y(n115),
	.B1(n182),
	.B0(B[0]),
	.A1(A[0]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U217 (
	.Y(n69),
	.B1(n182),
	.B0(B[1]),
	.A1(A[1]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U218 (
	.Y(n79),
	.B1(n182),
	.B0(B[4]),
	.A1(A[4]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U219 (
	.Y(n73),
	.B1(n182),
	.B0(B[2]),
	.A1(A[2]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U220 (
	.Y(n82),
	.B1(n182),
	.B0(B[5]),
	.A1(A[5]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U221 (
	.Y(n76),
	.B1(n182),
	.B0(B[3]),
	.A1(A[3]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U222 (
	.Y(n91),
	.B1(n182),
	.B0(N27),
	.A1(B[1]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U223 (
	.Y(n103),
	.B1(n182),
	.B0(N31),
	.A1(N10),
	.A0(B[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U224 (
	.Y(n100),
	.B1(n182),
	.B0(N30),
	.A1(N10),
	.A0(B[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U225 (
	.Y(n97),
	.B1(n182),
	.B0(N29),
	.A1(N10),
	.A0(B[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U226 (
	.Y(n94),
	.B1(n182),
	.B0(N28),
	.A1(N10),
	.A0(B[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U227 (
	.Y(n85),
	.B1(n182),
	.B0(B[6]),
	.A1(A[6]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U228 (
	.Y(n106),
	.B1(n182),
	.B0(N32),
	.A1(N10),
	.A0(B[6]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U229 (
	.Y(n109),
	.B1(n182),
	.B0(B[7]),
	.A1(A[7]),
	.A0(N10), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U230 (
	.Y(n112),
	.B1(n182),
	.B0(N33),
	.A1(N10),
	.A0(B[7]), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI22X1 U231 (
	.Y(n88),
	.B1(n182),
	.B0(N26),
	.A1(N10),
	.A0(B[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2X1 U232 (
	.Y(n55),
	.B(state[1]),
	.A(n198), 
	.VDD(VDD), 
	.VSS(VSS));
   NAND4X1 U233 (
	.Y(n65),
	.D(n119),
	.C(n118),
	.B(n201),
	.A(n194), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2X1 U234 (
	.Y(n118),
	.B(B[2]),
	.A(B[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   AND4X2 U235 (
	.Y(n119),
	.D(n156),
	.C(n154),
	.B(n200),
	.A(n164), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U236 (
	.Y(n199),
	.A(state[1]), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2X1 U237 (
	.Y(n56),
	.B(state[0]),
	.A(n199), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U238 (
	.Y(n183),
	.A(n54), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U239 (
	.Y(n54),
	.B1(A[7]),
	.B0(n56),
	.A2(A[7]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U240 (
	.Y(n190),
	.A(n63), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U241 (
	.Y(n63),
	.B1(n56),
	.B0(A[0]),
	.A2(A[0]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U242 (
	.Y(n185),
	.A(n58), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U243 (
	.Y(n58),
	.B1(n56),
	.B0(A[5]),
	.A2(A[5]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U244 (
	.Y(n186),
	.A(n59), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U245 (
	.Y(n59),
	.B1(n56),
	.B0(A[4]),
	.A2(A[4]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U246 (
	.Y(n187),
	.A(n60), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U247 (
	.Y(n60),
	.B1(n56),
	.B0(A[3]),
	.A2(A[3]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U248 (
	.Y(n188),
	.A(n61), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U249 (
	.Y(n61),
	.B1(n56),
	.B0(A[2]),
	.A2(A[2]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U250 (
	.Y(n189),
	.A(n62), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U251 (
	.Y(n62),
	.B1(n56),
	.B0(A[1]),
	.A2(A[1]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U252 (
	.Y(n184),
	.A(n57), 
	.VDD(VDD), 
	.VSS(VSS));
   AOI32X1 U253 (
	.Y(n57),
	.B1(n56),
	.B0(A[6]),
	.A2(A[6]),
	.A1(n192),
	.A0(n55), 
	.VDD(VDD), 
	.VSS(VSS));
   INVX1 U254 (
	.Y(n144),
	.A(rst_n), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2BX1 U258 (
	.Y(n146),
	.B(A[0]),
	.AN(B[0]), 
	.VDD(VDD), 
	.VSS(VSS));
   NOR2BX1 U259 (
	.Y(n145),
	.B(A[1]),
	.AN(n146), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI222XL U260 (
	.Y(n147),
	.C1(n161),
	.C0(B[2]),
	.B1(n145),
	.B0(B[1]),
	.A1(n162),
	.A0(n146), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI221XL U261 (
	.Y(n148),
	.C0(n147),
	.B1(n158),
	.B0(A[3]),
	.A1(n160),
	.A0(A[2]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI221XL U262 (
	.Y(n149),
	.C0(n148),
	.B1(n157),
	.B0(B[4]),
	.A1(n159),
	.A0(B[3]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI221XL U263 (
	.Y(n150),
	.C0(n149),
	.B1(n154),
	.B0(A[5]),
	.A1(n156),
	.A0(A[4]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI221XL U264 (
	.Y(n151),
	.C0(n150),
	.B1(n163),
	.B0(B[6]),
	.A1(n155),
	.A0(B[5]), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI2BB1X1 U265 (
	.Y(n152),
	.B0(n151),
	.A1N(B[6]),
	.A0N(n163), 
	.VDD(VDD), 
	.VSS(VSS));
   OAI2BB1X1 U266 (
	.Y(n153),
	.B0(n152),
	.A1N(A[7]),
	.A0N(n164), 
	.VDD(VDD), 
	.VSS(VSS));
endmodule

